### ISSUE TITLE
Option to disable DebugLogPopup and open DebugLogWindow on button press

### ISSUE THREAD

**Issue by RunninglVlan** [yasirkula/UnityIngameDebugConsole#10]
Your asset is really cool, thank you for that.
But could you add an option to disable _DebugLogPopup_. Right now it's only possible to _Start in Popup Mode_, or in _Window Mode_, but no option to _Disable Popup_ completely.
Currently I'm doing it this way:
- Deactivating _DebugLogPopup_
- Removing `DebugLogManager#popupManager`, adding `?.` to `popupManager` calls, e.g. `popupManager?.OnPointerClick( null );`
- Making `DebugLogManager#isLogWindowVisible` `public`
- Adding following code to some `MonoBehaviour#Update` with `debugManager`:
```
if (Input.GetKeyDown(KeyCode.F4)) {
  if (!debugManager.isLogWindowVisible) {
    debugManager.Show();
  } else {
    debugManager.Hide();
  }
}
```

Of course `KeyCode` for opening/closing window should be in options too to be able to modify it.

**Comment by yasirkula** [comment]
I guess I can add an option to replace the popup window with a key, yes. It is in my to-do list now.

**Comment by yasirkula** [comment]
See: https://github.com/yasirkula/UnityIngameDebugConsole/commit/bb0e088dc77dcd21691dec024b7efb43b45633fe
