### ISSUE TITLE
error add log

### ISSUE THREAD

**Issue by yingnierxiao** [yasirkula/UnityIngameDebugConsole#11]
Trying to add WarningCount (UnityEngine.UI.Text) for graphic rebuild while we are alreay inside  a graphic rebuild loop.this is not supported

**Comment by yasirkula** [comment]
Is a stacktrace provided in the log? If so, can I see the whole error message with stacktrace?

**Comment by yingnierxiao** [comment]
no stacktrace ,only this

**Comment by yasirkula** [comment]
Does this warning show up when doing something in particular?

**Comment by yingnierxiao** [comment]
no particular ，i use ohter log one,no this error.

**Comment by yasirkula** [comment]
Does importing [this unitypackage](https://github.com/yasirkula/UnityIngameDebugConsole/files/3389703/IngameDebugConsole.zip) (unzip first) to your project resolve the issue?

**Comment by yingnierxiao** [comment]
it's ok now
