### ISSUE TITLE
There are two problems in unity 5.5.4

### ISSUE THREAD

**Issue by ShenKang4181** [yasirkula/UnityIngameDebugConsole#12]
![image](https://user-images.githubusercontent.com/50401776/61943124-6342f600-afcd-11e9-8615-d2f77437e9d0.png)

**Comment by ShenKang4181** [comment]
Haha, I will upload the picture.

**Comment by yasirkula** [comment]
Thanks for reporting this. The minimum Unity version I'm supporting is 5.6, but I might resolve this issue in a future update, as well. For now, simply deleting those lines should work.

**Comment by ShenKang4181** [comment]
I have already done it, thank you, love you.
