### ISSUE TITLE
Were you considering adding sprites to atlas?

### ISSUE THREAD

**Issue by RunninglVlan** [yasirkula/UnityIngameDebugConsole#15]
Hi, were you considering creating sprite atlas? Or it doesn't do any good?

**Comment by yasirkula** [comment]
The sprites are using the legacy sprite packer which automatically packs sprites with the same _Packing Tag_ into the same atlas. For backwards compatibility, I'm not planning to switch to the new sprite atlases yet. But the process should be as simple as creating a new sprite atlas, adding all sprites to that atlas and disabling "Allow Rotation" and "Tight Packing". Unity will handle the rest automagically.
