### ISSUE TITLE
Logs do not appear when Debug.Log() called on async callback and not on main thread.

### ISSUE THREAD

**Issue by andrewspalato** [yasirkula/UnityIngameDebugConsole#17]
Hello, @yasirkula really love the UnityIngameDebugConsole and your awesome unity plugins, works great, but I have found that logs do not appear in the console if we are using asynchronous callbacks, is there a way to make these visible?

An example of this is using Firebase storage and their ContinueWith() Task callbacks.

The logs appear in adb logcat fine, but I would also like to see them inside the in game console too.

**Comment by yasirkula** [comment]
I'll try to reproduce the issue by calling Debug.Log in a separate thread, as soon as possible.

**Comment by yasirkula** [comment]
Can you unzip the attached archive and import the _unitypackage_ inside it to your project? I've updated the plugin and would appreciate it if you could give it a shot before I release the update publicly.

[IngameDebugConsole.zip](https://github.com/yasirkula/UnityIngameDebugConsole/files/4014445/IngameDebugConsole.zip)

**Comment by andrewspalato** [comment]
Thanks! This works but adding static commands will not work in a build from my test.

**Comment by yasirkula** [comment]
Do you mean the ConsoleMethod attribute? Did it work properly for the previous version? What are your build settings, e.g. IL2CPP, .NET 4.5, ProGuard minification and etc.?

**Comment by andrewspalato** [comment]
IL2CPP
.NET 4.5
Proguard Minify (using user proguard)

LogAllCommands and LogSystemInfo does not exist in DebugLogConsole.

**Comment by yasirkula** [comment]
This release should fix it: [IngameDebugConsole.zip](https://github.com/yasirkula/UnityIngameDebugConsole/files/4015145/IngameDebugConsole.zip)

**Comment by andrewspalato** [comment]
@yasirkula Thank you! Commands work, debug logs also work async. All works with Proguard enabled too.
