### ISSUE TITLE
Command added with DebugLogConsole.AddCommandInstance doesn't show up under "help" command.

### ISSUE THREAD

**Issue by Efmi** [yasirkula/UnityIngameDebugConsole#18]
I added a command using ```DebugLogConsole.AddCommandInstance()``` shown below. Command works fine when typed but it doesn't appear under the help command.

![image](https://user-images.githubusercontent.com/22080933/71676288-8649b100-2d88-11ea-8b17-abc63de15fc1.png)

I might have missed some steps to include the command under help, in which case the documentation should probably be improved.

- Plugin Version: v1.2
- Unity Version: 2019.2.17f1
- Operating System: Windows 10

**Comment by yasirkula** [comment]
Does this happen in a build or in the editor? If it is the former, are you using IL2CPP or Mono? Does changing the AddCommand function as follows make any difference: `DebugLogConsole.AddCommand<string>( "/tp", "changes to specified level", ChangeLevel );`

**Comment by Efmi** [comment]
It happens in the build, changing the command didn't help.
![image](https://user-images.githubusercontent.com/22080933/71677147-b6924f00-2d8a-11ea-9d01-6c23ee437d8c.png)

**Comment by Efmi** [comment]
It actually seems to popup into the editor log. The message just doesn't display all the commands.
![image](https://user-images.githubusercontent.com/22080933/71677409-71bae800-2d8b-11ea-8501-51bb7eb3d89e.png)

**Comment by yasirkula** [comment]
Oh, I see 😄 In-game console shows only the first two lines of the logs to save space. But you can click on logs to expand them and see the whole log.

**Comment by Efmi** [comment]
Oh, okay. Maybe the help command should call multiple messages to display the commands in that case? It is a bit confusing otherwise. 😄

**Comment by yasirkula** [comment]
Alternatively, you can expand the last log automatically when a console command is entered. To do so:

- Add this function to DebugLogRecycledListView.cs:

```csharp
public DebugLogItem GetLastLogItem()
{
	return logItemsAtIndices[currentBottomIndex];
}
```

- Add this code to DebugLogManager.OnValidateCommand function, right under the `SetSnapToBottom( true );` line:

```csharp
if( ( logFilter & DebugLogFilter.Info ) == DebugLogFilter.Info )
{
	LateUpdate();
	LayoutRebuilder.ForceRebuildLayoutImmediate( logItemsScrollRect.content );
	recycledListView.UpdateItemsInTheList( true );
	recycledListView.GetLastLogItem().OnPointerClick( nullPointerEventData );
}
```
