### ISSUE TITLE
Unity Package System Suggestion

### ISSUE THREAD

**Issue by RicardoBusta** [yasirkula/UnityIngameDebugConsole#20]
Hi.

I would like to suggest creating a branch where the project is set up as a Unity Package Manager. (e.g. upm)
It makes the project a lot easier to install since unity 2018.

As a suggestion, check how the Naughty Attributes Package did it some days ago:
https://github.com/dbrizov/NaughtyAttributes

Meanwhile, I forked the repo and changed a bit in order for it to work with the new package system:
https://github.com/RicardoBusta/UnityIngameDebugConsole
The directory structure is a bit messy, but was just to validate the idea. And it works great!

PS: Thanks for this awesome add-on!

**Comment by yasirkula** [comment]
Thank you for the suggestion and the example fork, it is indeed neatly organized with _.Source_ directory and etc. I'm currently not planning to change the layout of my repositories or maintain a separate fork, it is not a big task but I guess I'm lazy. Package Manager in Unity 2019.3 and later allows importing Asset Store packages, I think it will suffice for now.

**Comment by RicardoBusta** [comment]
Thanks!

It seems someone already published it on OpenUPM:
https://openupm.com/packages/com.yasirkula.ingame-debug-console/

**Comment by yasirkula** [comment]
Added Package Manager support with the latest release: https://github.com/yasirkula/UnityIngameDebugConsole/commit/b9a550865d88fd2ae61d792f48433b8c24b56458
