### ISSUE TITLE
Textmesh vertex limit

### ISSUE THREAD

**Issue by ElijahZAwesome** [yasirkula/UnityIngameDebugConsole#21]
I've run into an issue with this asset multiple times where my log is too large and the text in the in-game console doesn't get rendered and throws max vertices limit errors. The editor properly truncates the message, while this asset does not. I was able to hack together an easy solution but I wanted to let you know about it.

My solution:
At about line 506 I put in this line:
`
if(logString.Length >= maxLogLength) logString = logString.Remove(maxLogLength - stackTrace.Length) + "<Truncated>"; // Cut off log at a given limit minus the stacktrace length
`

**Comment by yasirkula** [comment]
Thanks for letting me know! Will apply your fix in the next release.
