### ISSUE TITLE
AutoComplete for param too

### ISSUE THREAD

**Issue by acgleader** [yasirkula/UnityIngameDebugConsole#25]
can you support param for autocompleting, like opencoding support, it is very convenient

**Comment by yasirkula** [comment]
I agree. Added to my to-do list but I may not push an update in the near future.

**Comment by yasirkula** [comment]
While reading the issue the first time, I thought that it was about `params type[]` support, I was wrong :) Parameter autocompletion is actually implemented by another user in this PR, could this be helpful to you: https://github.com/yasirkula/UnityIngameDebugConsole/pull/22

**Comment by yasirkula** [comment]
Related commit https://github.com/yasirkula/UnityIngameDebugConsole/commit/35b1287c03ae7f1bba48ad7dc1cb84a797d3894a. I don't plan to improve the console any further.
