### ISSUE TITLE
[Feature request] Add async commands support

### ISSUE THREAD

**Issue by AldeRoberge** [yasirkula/UnityIngameDebugConsole#28]
Would it be possible to add a way to call async commands?

        [ConsoleMethod("/register", "Create a new user")]
        public static async Task Register(string email, string password)
        {
            await _authenticationController.Register(email, password);
        }

**Comment by yasirkula** [comment]
You should be able to execute this command. The only downside is this unnecessary log:

![screenshot](https://user-images.githubusercontent.com/10211608/94854746-0e530900-0436-11eb-89b2-875afdc1d670.png)

The workaround for this log is to create a wrapper function instead:

```csharp
[ConsoleMethod("/register", "Create a new user")]
public static void RegisterUser(string email, string password)
{
    _ = Register(email, password);
}
```
