### ISSUE TITLE
Add document about the specification of pop-up, please

### ISSUE THREAD

**Issue by TakanoriHosoya** [yasirkula/UnityIngameDebugConsole#3]
The specification of the number displayed in the popup was not written in the readme.
![image](https://user-images.githubusercontent.com/7413235/39110862-bd60d046-470d-11e8-9d1d-48f51120af60.png)

As a result of verification, I understood that it is the number of unread logs output to the console window.
I felt that displaying unread counts is very good as a function.
I think that it would be easier to understand if the popup specification was written in the readme, so I would like to add it.

**Comment by yasirkula** [comment]
I've now updated the README.
