### ISSUE TITLE
New Input System

### ISSUE THREAD

**Issue by pirottedamien** [yasirkula/UnityIngameDebugConsole#31]
Hello, 
My project uses the new Input System package from Unity. When I start playing, Unity gives me an enormous amount of errors that the old Input System is used. I tried to change your code by myself to adapt it, but it kindof breaks everything... Could it be possible to mqke the plugin work with both versions of the Input System?

**Comment by yasirkula** [comment]
This issue exists on a number of my plugins. Yes, I must fix it to support both Input systems. Can't promise an ETA but it's in my to-do list.

**Comment by pirottedamien** [comment]
Ok, i'll stick with my solution then...

**Comment by yasirkula** [comment]
Won't add in the near future. https://github.com/yasirkula/UnityIngameDebugConsole/pull/32#issuecomment-735395202

**Comment by HyVong007** [comment]
I have the same problem. Hope you fix soon !

**Comment by nkholski** [comment]
I've got this issue too. Could it be possible to create a prefab that just render the debug-log without any interaction until this is solved?

**Comment by yasirkula** [comment]
Thank you all for your feedback. I'll prioritize this issue.

**Comment by yasirkula** [comment]
Addressed in https://github.com/yasirkula/UnityIngameDebugConsole/commit/6123ac72027a0cc2355465562ce598b96079351c
