### ISSUE TITLE
Null Ref with enableSearchbar = false

### ISSUE THREAD

**Issue by ddutchie** [yasirkula/UnityIngameDebugConsole#33]
**Description of the bug**

In DebugLogManager when enableSeachbar= false there is a null reference. 

Its due to 

`  if (!enableSearchbar)
            {
//This is set to null.
                searchbar = null;
                searchbarSlotTop.gameObject.SetActive(false);
                searchbarSlotBottom.gameObject.SetActive(false);
            }`

a few lines later

`  searchbar.GetComponent<InputField>().onValueChanged.AddListener(SearchTermChanged);`

is then null as you cleared the reference.

**Comment by yasirkula** [comment]
You are right. I must've moved AddListener line downwards in a recent update without thinking about the consequences. Will fix the issue ASAP.
