### ISSUE TITLE
Only Assembly-CSharp is supported for the ConsoleMethodAttribute

### ISSUE THREAD

**Issue by billw2012** [yasirkula/UnityIngameDebugConsole#39]
I use asmdefs for my game code, and so ConsoleMethodAttribute will not work. 
I changed your code to this and it works for me now:
```C#
foreach( var (method, attr) in AppDomain.CurrentDomain
    .GetAssemblies()
    .Where(a => !a.IsDynamic)
    .SelectMany(a => a.GetExportedTypes())
    .SelectMany(t => t.GetMethods( BindingFlags.Static | BindingFlags.Public | BindingFlags.DeclaredOnly ))
    .Select(m => (method: m, attr: m.GetCustomAttributes( typeof( ConsoleMethodAttribute ), false ).OfType<ConsoleMethodAttribute>().FirstOrDefault()))
    .Where(m => m.attr != null)
    )
{
	AddCommand( attr.Command, attr.Description, method );
}
```

**Comment by yasirkula** [comment]
Yes I'm aware of this limitation. That's why I like the DebugLogConsole.AddCommand functions. I'm inspecting only _Assembly-CSharp_ purely for performance reasons. I fear including all assemblies in the search would take significantly more time and it would be unpreferable for users who aren't interested in custom commands.

**Comment by billw2012** [comment]
A few things you could consider:
- Documenting this limitation, e.g. 
  > Simply add IngameDebugConsole.ConsoleMethod attribute to your functions. These functions must be public, static and must reside in a public class **in the Assembly-CSharp.dll assembly (i.e. if your code is in custom assemblies, as will happen if you use asmdefs, the attributes will not be detected)**.
- The amount of time it will take to iterate all types in the Assembly.CSharp.dll is already not under your control. It could still be slow if there is a lot of code.
- It takes ~130ms for me with no optimization, for me this is no problem for debug initialization code to take this long when it runs only once, however I have no doubt it could be optimized by a factor of 10 or more by e.g. excluding a bunch of known modules.

**Comment by billw2012** [comment]
I tried to optimize the assembly list and could only get it down to ~25ms by excluding modules based on name prefix (which isn't bullet proof), and company attribute value. This still left 14 out of 120 assemblies, all my plugins and game code.
Its a shame that module attributes are so inconsistently applied. e.g. having one generated automatically for each asmdef module would help in this case, but there isn't any such thing.

**Comment by yasirkula** [comment]
I've omitted most of the built-in assemblies from the search. Hopefully it will be pretty fast.
