### ISSUE TITLE
How to hide the persistent counter info?

### ISSUE THREAD

**Issue by andrew-sidereal** [yasirkula/UnityIngameDebugConsole#41]
This is a great asset -- thank you. 

I would just like to hide the hovering info window: https://i.imgur.com/lLL14Dj.png

I tried disabling it and other basic approaches, but it either breaks the asset or doesn't fully hide it. 

Before I tear into the code, what's the recommended way of hiding it? In my use case, nothing is shown until the user presses a hotkey to show the console.

**Comment by yasirkula** [comment]
It can be disabled via Enable Popup option of IngameDebugConsole object.
