### ISSUE TITLE
Possible Filtering Logs?

### ISSUE THREAD

**Issue by Bit00009** [yasirkula/UnityIngameDebugConsole#43]
Hi, Where should I start looking to prevent some logs of being displayed?
Like filtering them...

**Comment by yasirkula** [comment]
You can do so in either DebugLogManager.ReceivedLog (runs on a separate thread) or DebugLogManager.ProcessLog (runs on the main thread).

**Comment by Bit00009** [comment]
Thank you, Only one of them is enough?

**Comment by yasirkula** [comment]
Yep 😺
