### ISSUE TITLE
Input issue?

### ISSUE THREAD

**Issue by XeonG** [yasirkula/UnityIngameDebugConsole#45]
Just wondering what the solution is to this...
Active input handling is set to 'both'
2021.1.0b5
is there some compiler directive I can add to sort it out?

`NotSupportedException: The invoked member is not supported in a dynamic module.
System.Reflection.Emit.AssemblyBuilder.GetExportedTypes () (at <b54c5f8cbd8a46c6b18a2b3ef785ad6d>:0)
IngameDebugConsole.DebugLogConsole..cctor () (at Library/PackageCache/com.yasirkula.ingamedebugconsole@1.4.1/Plugins/IngameDebugConsole/Scripts/DebugLogConsole.cs:160)
Rethrow as TypeInitializationException: The type initializer for 'IngameDebugConsole.DebugLogConsole' threw an exception.
IngameDebugConsole.DebugLogManager.OnEnable () (at Library/PackageCache/com.yasirkula.ingamedebugconsole@1.4.1/Plugins/IngameDebugConsole/Scripts/DebugLogManager.cs:403)
`

`NotSupportedException: The invoked member is not supported in a dynamic module.
System.Reflection.Emit.AssemblyBuilder.GetExportedTypes () (at <b54c5f8cbd8a46c6b18a2b3ef785ad6d>:0)
IngameDebugConsole.DebugLogConsole..cctor () (at Library/PackageCache/com.yasirkula.ingamedebugconsole@1.4.1/Plugins/IngameDebugConsole/Scripts/DebugLogConsole.cs:160)
Rethrow as TypeInitializationException: The type initializer for 'IngameDebugConsole.DebugLogConsole' threw an exception.
IngameDebugConsole.DebugLogManager.RefreshCommandSuggestions (System.String command) (at Library/PackageCache/com.yasirkula.ingamedebugconsole@1.4.1/Plugins/IngameDebugConsole/Scripts/DebugLogManager.cs:960)
UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) (at <a3210ac464a241f0914b2746575c0be2>:0)
UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at <a3210ac464a241f0914b2746575c0be2>:0)
UnityEngine.UI.InputField.SendOnValueChanged () (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/InputField.cs:2276)
UnityEngine.UI.InputField.Insert (System.Char c) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/InputField.cs:2253)
UnityEngine.UI.InputField.Append (System.Char input) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/InputField.cs:2368)
UnityEngine.UI.InputField.KeyPressed (UnityEngine.Event evt) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/InputField.cs:1882)
UnityEngine.UI.InputField.OnUpdateSelected (UnityEngine.EventSystems.BaseEventData eventData) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/InputField.cs:1936)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IUpdateSelectedHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:106)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:272)
UnityEngine.EventSystems.EventSystem:Update() (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:501)
`

**Comment by yasirkula** [comment]
This issue has been fixed with this update: https://github.com/yasirkula/UnityIngameDebugConsole/commit/be7fc89e9d600c3caa5ba4effe8b85a63f747b30. Is your plugin up-to-date?

**Comment by XeonG** [comment]
yeah I am using that.. checked the code its the same.. no changes.. still same 2 error... first on play, and the others anytime a character is inputted into the input text area.

**Comment by XeonG** [comment]
1.4.1

**Comment by yasirkula** [comment]
I'd recommend you to delete the plugin completely and then reimport it. If it still doesn't work, try importing the plugin [from GitHub](https://github.com/yasirkula/UnityIngameDebugConsole/releases/tag/v1.4.1). Unlikely but perhaps I uploaded the old files to Asset Store?

**Comment by XeonG** [comment]
hmm well that seems to work better.. weird because I did replace the package contents with latest... but its like it wasn't picking up the changes from that location, as I don't get that error now...oh well better in the project had some minor changes to make anyway
