### ISSUE TITLE
Rewired/Unity default input seems to override the asset's input

### ISSUE THREAD

**Issue by zadda** [yasirkula/UnityIngameDebugConsole#5]
Hi,

Thank you very much for making this (and your other) asset freely available, this one definitely seems to be what I am looking for. 

I may be overlooking something or am just not good enough at Unity/coding but when I dropped this asset in my project I am unable to click on the icons as I've already have the mouse click function used in game as an attack function and that seems to take priority. Would it be possible for a keyboard  toggle(preferably self assignable) to be added or is there another solution you would suggest to potentially resolve this?

Thanks and kind regards,
Mike

**Comment by yasirkula** [comment]
Functions like Input.GetMouseButton shouldn't interfere with this plugin. Is there a large UI canvas with Sort Order >= 1001 in your scene? Which Unity version are you using? What happens when you create a UI-EventSystem object in your scene? Are there any exceptions thrown by this plugin in the console?

**Comment by zadda** [comment]
There is a UI canvas in the scene 1317x636 with sort order 0. 
I'm using the latest Unity version 2018.3.0f2.
When I create a new UI eventsystem in the editor it jumps straight to the eventsystem of the debugconsole prefab.

There are no exceptions thrown by this plugin. The only thing I see in the console is the following line.
"rewired currently overriding Unity Input: to disable input override permanently delete UnityInputOverride.cs

**Comment by zadda** [comment]
No it does not, but I found out what caused the problem. I had a script with Cursor.lockState in awake event. Disabling that script made the the console interactable. Even though in the editor I could show the cursor again by hitting the escape key that was not enough apparently. Also normally the cursor lock state was only in the editor not in the build. Either way, it works now so thanks again for providing this asset and for your quick support!
Kind regards,
