### ISSUE TITLE
[UWP] How to use InGameDebugConsole In Universal Windows Platform ?

### ISSUE THREAD

**Issue by ArtGo-Devloppper** [yasirkula/UnityIngameDebugConsole#50]
Hello,
I want to use your plugin in UWP but the console didn't show in build.
In the editor she work 
did you have any solutions ?

**Comment by yasirkula** [comment]
Not really. If the build doesn't fail, I don't see any reason for the console to disappear in build. Are you sure that IngameDebugConsole exists in the scene you are building (you have to put it in the scene manually, it isn't automatically spawned)? If you are sure, can you see any error messages in Unity's log file: https://docs.unity3d.com/Manual/LogFiles.html
