### ISSUE TITLE
Disable CS0169 warning in DebugLogManager.logcatArguments

### ISSUE THREAD

**Issue by Trisibo** [yasirkula/UnityIngameDebugConsole#56]
It would be nice to add a `#pragma warning disable 0169` for the field `DebugLogManager.logcatArguments`.

**Comment by yasirkula** [comment]
Do you see this warning in Unity console or only in your IDE? If it is the former, when does the warning show up?

**Comment by Trisibo** [comment]
In Unity's console, it appears at least when installing the plugin, when changing the build platform, and when building on platforms that aren't Android. But only when the option "Suppress Common Warnings" in the player settings is disabled. Not a big deal, but if you could add that if/when you make a new version it would be the cherry on top :)

**Comment by yasirkula** [comment]
Will do, thanks! I'll close the issue when I push an update.
