### ISSUE TITLE
would you pls support copy/paste on webgl platform?

### ISSUE THREAD

**Issue by Bian-Sh** [yasirkula/UnityIngameDebugConsole#58]
and float panel maybe taste good.

**Comment by yasirkula** [comment]
So, the **Copy button** located at the bottom of the selected log doesn't work on WebGL, am I right? If so, with which Unity version did you build your app?

**Comment by Bian-Sh** [comment]
I use unity 2020.3.0f1c1 
but maybe copy/paste is not supported by unity player on webgl .
and, there is a repo for patch: https://github.com/greggman/unity-webgl-copy-and-paste

**Comment by yasirkula** [comment]
The latest commit worked properly on Chrome and Edge for me.

**Comment by Bian-Sh** [comment]
cheer up，you did great job，thanks！
