### ISSUE TITLE
Timestamps of log entries

### ISSUE THREAD

**Issue by sceeter89** [yasirkula/UnityIngameDebugConsole#59]
Hi! Firstly I'd like to stress that we're using your asset and we find it very valuable, useful and stable. Thank you for your great work! There is one thing however we (and possible others) would find useful:

When log entry is expanded, it would be great to see when entry was logged. Perfectly with both local time, frame # and Time.time.

**Comment by yasirkula** [comment]
Yes, it would be useful. But isn't local time enough information? Unity's console shows only local time, for example.

**Comment by sceeter89** [comment]
It would, as we can compute Time.time by subtracting first and selected log entry, however it gets messy if we clear logs. Then it's getting harder to tell if game was just started or was running for some time. While not mandatory, when working with QA it might be useful as we don't have to rely on remembering.

Anyway local time would be great, other information could come in handy sometime.

**Comment by yasirkula** [comment]
Please give the latest version a try 🤓

**Comment by sceeter89** [comment]
I've just checked 1.5.1 version and it's exactly what I meant. Thank you for your help and great asset! :)

**Comment by yasirkula** [comment]
Happy to help 🥳
