### ISSUE TITLE
Feature request - Popup, gesture and support email

### ISSUE THREAD

**Issue by omid3098** [yasirkula/UnityIngameDebugConsole#6]
Hello.
It would be awesome if we have options to auto popup on error, using gestures like swipe down with two fingers to show the console and have email fields for sending full log to support email address.

**Comment by yasirkula** [comment]
Thank you for the feature requests! These are all useful features but I am currently trying to achieve similar results via the popup that shows up when you close the console.

Maybe I can add a built-in command (like `help`) to write the logs to a file or share them via email or some other medium. I may not be able to implement this feature soon, though, as I am working on some other projects at the moment.
