### ISSUE TITLE
I think a command  should be added to hide popwindow below

### ISSUE THREAD

**Issue by Bian-Sh** [yasirkula/UnityIngameDebugConsole#60]
![image](https://user-images.githubusercontent.com/24520547/129003381-c87743eb-b68d-4f1c-ab60-d30731df5791.png)

a command named，emmm... , perhaps "pophide/popshow" ，and save changes to PlayerPrefs should be good. 
if possible how about adding a setting panel for UnityIngameDebug Console itself .

**Comment by yasirkula** [comment]
You mean a console command to disable the popup? If a user did that, how would they open the console window again?

Settings panel is a common occurrence in such plugins and would be a nice addition to this plugin, as well. I don't have time for this feature right now but in the future, why not.

**Comment by Bian-Sh** [comment]
Q:how would they open the console window again?
A: For Standalone Platform use shortcut "~" and for mobile app just set a simple guesture as this [repo](https://github.com/chiuan/TTConsole) do.

**Comment by yasirkula** [comment]
Developers can already disable the popup via IngameDebugConsole prefab's inspector and set the shortcut key as they desire. Plugin doesn't have built-in gesture detection but developers can implement gesture detection on their own and toggle the console window via DebugLogManager.Instance functions. If a developer configured the popup to be visible, I don't think users should have the ability to disable the popup; the developer enabled the popup for a reason.

If you want to give users the ability to toggle popup's visibility in your project, you can add the following command to your script:

```csharp
[ConsoleMethod( "popup_off", "Disables the debug popup" )]
public static void DisablePopup( Vector3 position )
{
	DebugLogManager.Instance.PopupEnabled = false;
}
```

**Comment by Bian-Sh** [comment]
yes ,add this command can enrich internal commands of this plugin but actully  is not necessary ;
