### ISSUE TITLE
[Suggestion] Change scripts accessibility levels

### ISSUE THREAD

**Issue by bguyl** [yasirkula/UnityIngameDebugConsole#61]
**Suggestion**

I installed the console through OpenUPM, it works super well ! Congrats

For my project, I need to make some small changes. I can't directly change the `DebugLogManager` script as files in a package are read only.

What would be great would be to let people inherit from scripts, so they can adapt the code without directly modifying the package.

Changes that would be welcoming:
- Change accessibility levels of fields and methods from `private` to `protected`
- Tag methods as `virtual`

**Comment by yasirkula** [comment]
Thank you for your support and the suggestion. I'm not very optimistic about this idea at the moment and I'd recommend you to install the plugin as a normal asset and modify its source code instead. You can also move the plugin's files to Packages folder via file explorer, which will include the plugin in version control and allow you to modify its source code; Unity will continue showing the plugin under Packages folder.
