### ISSUE TITLE
[Request PS4 support] Hi there, we are developing an indiegame on PS4 and I found this plugins can not run on PS4.

### ISSUE THREAD

**Issue by wavebbs** [yasirkula/UnityIngameDebugConsole#62]
Could you please add PS4 support.
Thank you so much!

**Comment by yasirkula** [comment]
In that case, which parts of the debug console are currently not responsive while using a USB keyboard/mouse?

**Comment by yasirkula** [comment]
Feel free to reopen the Issue.
