### ISSUE TITLE
Nintendo Switch and BoatAttack - The interface freezes and I can't interact

### ISSUE THREAD

**Issue by ImanCol** [yasirkula/UnityIngameDebugConsole#68]
I am using UnityIngameDebugConsole with BoatAttack project and running on Nintendo Switch.

When I load a different scene where I have assigned the prefab, the entire interface (touch) is disabled so I cannot close or open the console, as well as move around the game interface.

This only happens during a race or demo. In the demo it automatically returns to the Menu at the end of the race and the interface works again.

I have placed the IngameDebugConsole prefab in the "main_menu" scene when executed it scrolls as a child_object inside a temporary scene called DontDestroyOnLoad and is still present when another scene loads so I think it is not necessary to place the IngameDebugConsole prefab inside the scene another scene like level_Island.

When running it inside the Engine it still works correctly when loading another scene, only when I compile it on Switch the whole interface freezes when loading another scene where the IngameDebugConsole prefab had been assigned.

VIDEO:
[![Everything Is AWESOME](https://user-images.githubusercontent.com/26169049/161849329-ff4f776e-327a-4b00-b5f5-303b4ae0188f.jpg)](https://youtu.be/YJeGfYoUUDA
"Everything Is AWESOME")

![image](https://user-images.githubusercontent.com/26169049/161847430-7f90b9d3-c033-4c7c-b5cc-4dda1dbbcccf.png)
![image](https://user-images.githubusercontent.com/26169049/161847490-0cfc5a25-e0c8-479e-966b-acb0fdc99ab8.png)

**Comment by ImanCol** [comment]
If I assign the IngameDebugConsole prefab to the level_island scene, it works when it returns to main_menu, which doesn't have it.

**Comment by yasirkula** [comment]
I'd recommend you to deactivate IngameDebugConsole prefab's Event System child object and put an Event System to those scenes manually if one doesn't exist.
