### ISSUE TITLE
[Feature request] Collect logs when disabled

### ISSUE THREAD

**Issue by Romaleks360** [yasirkula/UnityIngameDebugConsole#70]
In our project, we have a secret debug menu that opens with a key combination and contains useful stats (and the debug console, obviously). Menu is disabled on start to save screen space, and we only need it when something weird happens in the game. We need this debug menu in development builds for alpha-testers, but we don't want it to be discovered by everyone, hence the key combination. Seems like a pretty common use case for me. 
Currently, the console is not collecting logs when disabled. This should be an option in properties.

**Comment by yasirkula** [comment]
Fixed with release v1.5.6: the property "Receive Logs While Inactive" is disabled by default. Please make sure to read the property's tooltip, though.
