### ISSUE TITLE
[Feature request] Supports safe area.

### ISSUE THREAD

**Issue by Haruma-K** [yasirkula/UnityIngameDebugConsole#71]
Thanks for your great library.

On mobile platforms, the DebugLogPopup goes outside the safe area.
I think it would be better if there is an option to limit it to within the safe area.

![image](https://user-images.githubusercontent.com/47441314/184167750-9f60ab5b-3c1b-4d0c-9fc7-d747348b1f92.png)

**Comment by Haruma-K** [comment]
Thank you! I'm looking forward to it.

**Comment by Haruma-K** [comment]
Thanks! It's working very well!

**Comment by yasirkula** [comment]
Happy to hear that :)
