### ISSUE TITLE
Android Log is not work

### ISSUE THREAD

**Issue by GGDevLee** [yasirkula/UnityIngameDebugConsole#73]
receiveLogcatLogsInAndroid is true , my huawei phone is android12, but i still can't receive android log

**Comment by yasirkula** [comment]
Android will return only the app's logcat logs, unfortunately. But this includes logs like AdMob's which can only be viewed via receiveLogcatLogsInAndroid, yes. Are you receiving absolutely zero logs that start with "LOGCAT"?
