### ISSUE TITLE
Are there any files stored all logs?

### ISSUE THREAD

**Issue by pikapikapii** [yasirkula/UnityIngameDebugConsole#76]
When close my ingame console in game, all logs were gone.
Are there any files stored all logs?
It can help a lot when debug

**Comment by pikapikapii** [comment]
Just found out help command...
very useful!

**Comment by yasirkula** [comment]
The best you can do is calling the logs.save command :) There isn't a built-in way to automatically save the logs to a file in IngameDebugConsole.
