### ISSUE TITLE
Logs inside a catch

### ISSUE THREAD

**Issue by dryn27** [yasirkula/UnityIngameDebugConsole#8]
Hey! I just realiced this asset is not showing me logs inside the try&catch. I am not sure why. Is there any solution to this?

**Comment by yasirkula** [comment]
Unexpected for me. This plugin fetches logs from the Application.logMessageReceived event. Try registering it to yourself for testing purposes and see if you receive the logs inside try-catch blocks.

**Comment by yasirkula** [comment]
The following code works on 5.6.2f1:

```csharp
try
{
	int i = 0;
	Debug.Log( 1 / i );
}
catch( Exception e )
{
	Debug.LogException( e );
}
```
