### ISSUE TITLE
Disable unity input manager

### ISSUE THREAD

**Issue by ddsurvivor** [yasirkula/UnityIngameDebugConsole#87]
When using old input manager, if it is possible to add a feature to disable the input manager? So that my character will not running when I texting "ad".

**Comment by yasirkula** [comment]
I think the best you can do is check if an InputField has focus and if so, ignore wasd keys in your player movement script:

```csharp
EventSystem eventSystem = EventSystem.current;
return !eventSystem || !eventSystem.currentSelectedGameObject || !eventSystem.currentSelectedGameObject.TryGetComponent(out InputField inputField) || !inputField.isFocused;
```
