### ISSUE TITLE
Unconstrained memory usage due to log entries

### ISSUE THREAD

**Issue by webcoyote** [yasirkula/UnityIngameDebugConsole#88]
The `DebugLogConsole` aggregates log entries forever because old entries are not pruned, so it can consume a lot of memory (especially if stack traces are not disabled). Specifically, the `collapsedLogEntries` and related arrays grow without bound.

An alternative would be to replace the collapsed/uncollapsed log entries with bounded circular lists, which would be simpler, I think? Devs could then set whatever bounds they think reasonable.

On a minor note, it looks to be the case that `DebugLogIndexList<T>` can be replaced with `List<T>` with no loss of functionality, except that `new DebugLogIndexList<T>()` calls need to be converted to `new List<T>(64)` to have similar initial allocations.

Your plugin is great; it otherwise works really well! Thanks!

**Comment by yasirkula** [comment]
Thank you for the sponsorship! This optional feature could be implemented with considerable effort, yeah. I'll add it to my to-do list but I can't promise a quick solution due to my current work schedule.

I've created the DebugLogIndexList to avoid unnecessary checks/operations of the List class for maximum performance. The initial motivation was the unnecessary Array.Clear call in `List<int>.Clear`.

**Comment by webcoyote** [comment]
Totally understand about  workload, esp. since you're giving away the plugin!

In regards to calling `Array.Clear`, while it's marginally faster, my understanding is that it only zeroes the individual items if they're objects, which is desirable so that they don't hang around in memory indefinitely, clogging up the heap: https://referencesource.microsoft.com/#mscorlib/system/array.cs,342. Since the Clear call is only infrequently used, I wouldn't think it would have a speed impact. In any case, it's a small matter either way, just thought I'd mention it

**Comment by yasirkula** [comment]
After working on this for way, way too long, it's finally ready. In my tests I didn't encounter any issues but I really hope that I didn't miss anything. I've also applied other important optimizations to the codebase along the way. I'd like to hear your test results when you get the chance to test it.
