### ISSUE TITLE
README.md does not match README.txt

### ISSUE THREAD

**Issue by sandsalamand** [yasirkula/UnityIngameDebugConsole#89]
The most recent commit, 050991e, changed README.txt to show that manual modifications are no longer necessary to use the new Input System, but README.md still shows that they are.

**Comment by yasirkula** [comment]
I've listed the edge cases on README.md's FAQ list. These edge cases apply to Unity 2019.2.5 or earlier. On later versions, no manual setup is needed.

**Comment by yasirkula** [comment]
Oh wait...
