### ISSUE TITLE
After running, output a NullReferenceException every second.Until focus game panel.

### ISSUE THREAD

**Issue by ShenKang4181** [yasirkula/UnityIngameDebugConsole#93]
![image](https://github.com/yasirkula/UnityIngameDebugConsole/assets/50401776/af6e2c39-f07b-4d6e-bbb7-ed2c0d296ad7)

my unity version : 2020.3.48
This is a detailed log
NullReferenceException: Object reference not set to an instance of an object
UnityEngine.UI.InputField.GenerateCaret (UnityEngine.UI.VertexHelper vbo, UnityEngine.Vector2 roundingOffset) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/InputField.cs:2770)
UnityEngine.UI.InputField.OnFillVBO (UnityEngine.Mesh vbo) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/InputField.cs:2700)
UnityEngine.UI.InputField.UpdateGeometry () (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/InputField.cs:2661)
UnityEngine.UI.InputField.Rebuild (UnityEngine.UI.CanvasUpdate update) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/InputField.cs:2613)
UnityEngine.UI.CanvasUpdateRegistry.PerformUpdate () (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/CanvasUpdateRegistry.cs:215)
UnityEngine.Canvas:SendWillRenderCanvases()

**Comment by yasirkula** [comment]
I haven't encountered this issue before. When does this occur?

**Comment by ShenKang4181** [comment]
Yes, it will happen every second until I click on the game panel. Do I need to provide anything else like log?

**Comment by ShenKang4181** [comment]
This problem is new in version 1.6.7.

**Comment by yasirkula** [comment]
Not much has changed in 1.6.7 though. Are you sure this didn't happen on 1.6.6?

**Comment by ShenKang4181** [comment]
yes,i sure this didn't happen on 1.6.6 
![image](https://github.com/yasirkula/UnityIngameDebugConsole/assets/50401776/3083de91-54b4-4f9d-913c-753c9932e1f2)

**Comment by yasirkula** [comment]
If you put an unmodified IngameDebugConsole prefab to your scene and deactivate the modified one (for testing purposes), does the problem still occur for the completely unmodified prefab instance? If not, could you try to pinpoint exactly which modification causes this issue?

**Comment by ShenKang4181** [comment]
I was sure it would embarrass you, so I solved the problem myself.i add CanvasGroup to IngameDebugConsole and control alpha
Thank you anyway.

**Comment by yasirkula** [comment]
I couldn't reproduce the issue on 2021.3.29f1 (just disabled Canvas, no other changes).

I'd recommend checking out the following settings because maybe you won't need to add a CanvasGroup at all: Start Minimized, Popup Visibility, Toggle Key

**Comment by ShenKang4181** [comment]
oh！ I have never seen this before, and now I have learned it.and I have an idea how to open it on a mobile device？

**Comment by yasirkula** [comment]
In my project, I've set Popup Visibility to "When Log Received" and changed log filter to only _Error_ so that when an error is encountered, the popup is automatically shown. But you could also fully disable the popup and when you want to display the debug console (e.g. when 3 fingers are held at screen), call `DebugLogManager.Instance.ShowLogWindow();` in your script.

**Comment by ShenKang4181** [comment]
I get, thank you. ✌︎(ツ)ɔ
