### ISSUE TITLE
Support Method Overloading with `DebugLogConsole.AddCommand`

### ISSUE THREAD

**Issue by CompuGenius-Programs** [yasirkula/UnityIngameDebugConsole#94]
**Description of the bug**

I have a function `SaveScore` which can take either a username (string) or user index (int) and a score (int). I tried adding them to the DebugLogConsole using
```cs
DebugLogConsole.AddCommand<string, int>("savescore", "Save a player's score by name.", SaveScore);
DebugLogConsole.AddCommand<int, int>("savescore", "Save a player's score by index.", SaveScore);
```
but only the string one gets called. The other one does nothing.

I also have a function called `LoadScore` that takes either a username (string) or user index (int). The only way to add either to the DebugLogConsole is by adding both parameter types, like so:
```cs
DebugLogConsole.AddCommand<string, int>("loadscore", "Load a player's score by name.", LoadScore);
```
However, here too, even if I add one for the int method, only the string one gets called and the int does nothing:
```cs
DebugLogConsole.AddCommand<string, int>("loadscore", "Load a player's score by name.", LoadScore);
DebugLogConsole.AddCommand<int, int>("loadscore", "Load a player's score by index.", LoadScore);
````

**Reproduction steps**

Create a function with a parameter and an overload function with a parameter of a different type. Add both to `DebugLogConsole.AddCommand`. Only the first gets recognized.

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: *2022.2.4f1*
- Platform: *All*
- How did you download the plugin: *Package Manager*

**Comment by yasirkula** [comment]
I'm sorry for the long wait 😿 I've found a very simple fix for this issue: simply register the int method before the string method. That's because the console goes through all commands and tries to parse the input parameters by looking at the command signature. You can cast anything to string which is why it'll accept any input you pass to it. But if the int method is parsed first, then all int inputs are forwarded to that command and remaining inputs are forwarded to the string command.

**Comment by CompuGenius-Programs** [comment]
> You can cast anything to string which is why it'll accept any input you pass to it. But if the int method is parsed first, then all int inputs are forwarded to that command and remaining inputs are forwarded to the string command.

Ah, interesting! I didn't even think of that, although in hindsight that's pretty obvious. I'm afk for the next few days, but am eager to try it out and report back!

**Comment by CompuGenius-Programs** [comment]
@yasirkula that solution worked, thank you! Although obvious in hindsight, perhaps add a note to the documentation in case anyone else has an issue with this.
