### ISSUE TITLE
Missing Recycled List View

### ISSUE THREAD

**Issue by CorbyO** [yasirkula/UnityIngameDebugConsole#98]
**Description of the bug**
Recycled List View is missing in Debug Log Manager and also i can't found it in hierarchy. so console is not work
![image](https://github.com/user-attachments/assets/104dcdf6-fbc5-4798-b9db-dfdb88627746)
![image](https://github.com/user-attachments/assets/a3b0a784-c982-4ad9-883f-88c0244b0371)
![image](https://github.com/user-attachments/assets/64de262e-9dc3-4ac6-ac4d-c62caa4c6f0c)

**Reproduction steps**
It is ok when first download and can see the bug later

**Platform specs**

- Unity version: 2022.3.37f1
- Platform: Editor(Android)
- How did you download the plugin: OpenUPM
- this asset version: 1.6.9

**Comment by CorbyO** [comment]
Bug is fixed after remove library folder.

**Comment by yasirkula** [comment]
Deleting Library folder could take a lot of time so I'd recommend first right clicking the IngameDebugConsole folder and selecting Reimport the next time something similar happens.

**Comment by CorbyO** [comment]
I haven‘t done that. If I see the same bug again, I‘ll do it. Thank you!!
